### ISSUE TITLE
Look nice but I cannot find a live site

### ISSUE THREAD

**Issue by dgeibi** [habblism/NetBar#1]
You can try Heroku. Demo here: https://github.com/heroku/devcenter-java

**Comment by habblism** [comment]
x

**Comment by backslasha** [comment]
thanks master dgeibi for advance, but that's looks complicated for us vegetable birds ↶ ␣ ↶
I brought a cloud server from tencent with 1 RMB per month, and i did post the app up .
here is the live site: [just looks too dump to be giving out](http://123.207.59.126:8080/NetBar)

**Comment by dgeibi** [comment]
I can't login😂

**Comment by habblism** [comment]
boss accont : $my_second_name_full_pinyin+"123"
password: 123456
